version: '3.8'

services:
  # 메인 애플리케이션 서비스
  mediapipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediapipe_sign_language
    image: mediapipe-sign-language:latest
    
    # 볼륨 마운트 (데이터 영속성)
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config.yaml:/app/config.yaml
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 소켓 (GUI)
      - /dev/video0:/dev/video0  # 카메라 디바이스 (Linux)
    
    # 환경 변수
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    
    # 디바이스 접근
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd  # 오디오 디바이스
    
    # 특권 모드 (카메라 접근용)
    privileged: true
    
    # 네트워크 설정
    network_mode: host
    
    # 재시작 정책
    restart: unless-stopped
    
    # 기본 명령어 오버라이드 (주석 처리)
    # command: python main.py inference
    
    # stdin/tty (인터랙티브 모드)
    stdin_open: true
    tty: true

  # 데이터 수집 서비스
  data-collector:
    extends: mediapipe-app
    container_name: mediapipe_data_collector
    profiles:
      - data-collection
    command: python main.py collect --label "test" --samples 10

  # 모델 학습 서비스
  trainer:
    extends: mediapipe-app
    container_name: mediapipe_trainer
    profiles:
      - training
    command: python main.py train --data data/raw
    # GPU 지원 (NVIDIA Docker)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # 추론 서비스
  inference:
    extends: mediapipe-app
    container_name: mediapipe_inference
    profiles:
      - inference
    command: python main.py inference

volumes:
  data:
    driver: local
  models:
    driver: local
